variables:
  terraformWorkingDirectoryName: 'tf\core\src'
  terraformWorkingDirectory: '$(System.DefaultWorkingDirectory)\$(terraformWorkingDirectoryName)'
  settingsDirectory: '$(System.DefaultWorkingDirectory)\settings'
  testsDirectoryName: 'tests'
  featuresDirectoryName: 'features'
  testsDirectory: '$(System.DefaultWorkingDirectory)\$(testsDirectoryName)'
  outputDirectory: '$(System.DefaultWorkingDirectory)\output'
  testresultsDirectoryName: 'testresults'
  testresultsDirectory: '$(System.DefaultWorkingDirectory)\$(testresultsDirectoryName)'
