trigger:
  branches:
    include:
    - '*'

variables:
- template: azure-pipelines-armsettings.yml
- template: azure-pipelines-directories.yml
- template: azure-pipelines-toolversions.yml

parameters:
- name: testresultspublish
  displayName: 'Publish test results after CI?'
  type: boolean
  default: true
- name: terraformcompliancedocker
  displayName: 'Run terraform-compliance via Docker container?'
  type: boolean
  default: false

stages:
  - stage: CI_Terratest
    displayName: CI_Terratest
    variables:
    - group: Azure-auth-vargroup
    jobs:
    - job: CI_Terratest1
      pool:
        vmImage: windows-latest
      displayName: CI_Terratest1
      steps:
      - task: CmdLine@2
        displayName: 'make directories'
        inputs:
          script: |
            mkdir $(outputDirectory)
            mkdir $(testresultsDirectoryWindows)      
      - task: UsePythonVersion@0
        displayName: 'use Python version'
        inputs:
          versionSpec: '$(pythonVersion)'
          addToPath: true
          architecture: 'x64'
      - task: TerraformInstaller@0
        displayName: 'install Terraform'
        inputs:
          terraformVersion: $(terraformVersion)
      - task: GoTool@0
        displayName: 'install Go'
        inputs:
          version: '$(goVersion)'
      - task: CmdLine@2
        displayName: 'run Terratest'
        inputs:
          script: |
            go test -v | tee terratest.log
          workingDirectory: '$(testsDirectoryTerraTest)'
        env:
          ARM_CLIENT_ID: $(ARM_CLIENT_ID)
      - task: CmdLine@2
        displayName: 'run Terratest Log Parser'
        inputs:
          script: |
            curl --location --silent --fail --show-error -o terratest_log_parser.exe https://github.com/gruntwork-io/terratest/releases/download/v$(terratestlogparserVersion)/terratest_log_parser_windows_amd64.exe
            terratest_log_parser.exe -testlog terratest.log -outputdir $(testresultsDirectoryWindows)
          workingDirectory: '$(testsDirectoryTerraTest)'
      - task: PublishTestResults@2
        displayName: 'publish test results'
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: '$(testresultsDirectoryWindows)\*report.xml'
        condition: eq(${{ parameters.testresultspublish }}, true)

  - stage: CI_TerraformAndOSSTools
    dependsOn: []
    displayName: CI_TerraformAndOSSTools
    variables:
    - group: Azure-auth-vargroup
    jobs:
    - job: CI_TerraformAndOSSTools1
      pool:
        vmImage: ubuntu-latest
      displayName: CI_TerraformAndOSSTools1
      steps:
      - task: CmdLine@2
        displayName: 'make directories'
        inputs:
          script: |
            mkdir $(outputDirectory)
            mkdir $(testresultsDirectoryLinux)
      - task: UsePythonVersion@0
        displayName: 'use Python version'
        inputs:
          versionSpec: '$(pythonVersion)'
          addToPath: true
          architecture: 'x64'
      - task: TerraformInstaller@0
        displayName: 'install Terraform'
        inputs:
          terraformVersion: $(terraformVersion)
      - task: CmdLine@2
        displayName: 'install OSS Tools'
        inputs:
          script: |
            pip install "checkov==$(checkovVersion)"
            pip install "terraform-compliance==$(terraformcomplianceVersion)"
      - task: TerraformCLI@0
        displayName: 'run Terraform init'
        inputs:
          command: init
          workingDirectory: '$(terraformWorkingDirectoryLinux)'
          allowTelemetryCollection: false
      - task: TerraformCLI@0
        displayName: 'run Terraform validate'
        inputs:
          command: validate
          workingDirectory: '$(terraformWorkingDirectoryLinux)'
          allowTelemetryCollection: false
      - task: TerraformCLI@0
        displayName: 'run Terraform plan'
        inputs:
          command: 'plan'
          workingDirectory: '$(terraformWorkingDirectoryLinux)'
          commandOptions: '-out=$(terraformWorkingDirectoryLinux)/$(terraformPlanFile)'
          allowTelemetryCollection: false

      - task: CmdLine@2
        displayName: 'run Terraform show'
        inputs: 
          script: |
            cd $(terraformWorkingDirectoryLinux)
            terraform show -json $(terraformWorkingDirectoryLinux)/$(terraformPlanFile) > $(terraformWorkingDirectoryLinux)/$(terraformPlanFileJSON)
        condition: eq(${{ parameters.terraformcompliancedocker }}, true)
        continueOnError: true
  
      - task: CmdLine@2
        displayName: 'run Checkov'
        inputs:
          script: |
            checkov --soft-fail --directory $(terraformWorkingDirectoryLinux) --skip-check $(checkovSkipChecks) --output junitxml > $(testresultsDirectoryLinux)/test-checkov-report.xml
        continueOnError: true

      - task: CmdLine@2
        displayName: 'run terraform-compliance via local install'
        inputs:
          script: |
            terraform-compliance --no-ansi -n -p $(terraformWorkingDirectoryLinux)/$(terraformPlanFile) -f $(testsDirectory)/features --junit-xml $(testresultsDirectoryLinux)/test-terraformcompliance-report.xml
        condition: eq(${{ parameters.terraformcompliancedocker }}, false)
        continueOnError: true

      - task: DockerInstaller@0
        inputs:
          dockerVersion: '17.09.0-ce'      
        condition: eq(${{ parameters.terraformcompliancedocker }}, true)
        continueOnError: true
      - task: CmdLine@2
        displayName: 'run terraform-compliance via Docker container'
        inputs:
          script: |
            docker run --rm -v "$(System.DefaultWorkingDirectory)":/target $(terraformcomplianceDockerimage):$(terraformcomplianceVersion) --no-ansi -n -f $(testsDirectoryName)/$(featuresDirectoryName) -p $(terraformWorkingDirectoryNameLinux)/$(terraformPlanFileJSON) --junit-xml $(testresultsDirectoryName)/test-terraformcompliance-report.xml
        condition: eq(${{ parameters.terraformcompliancedocker }}, true)
        continueOnError: true

      - task: PublishTestResults@2
        displayName: 'publish test results'
        inputs:
          testResultsFormat: 'JUnit'
          testResultsFiles: '$(testresultsDirectoryLinux)/*report.xml'
        condition: eq(${{ parameters.testresultspublish }}, true)
